### ISSUE TITLE
请问有声效资源吗？

### ISSUE THREAD

**Issue by Ryuchen** [TomyJan/WutheringWaves-UIResources#1]
非角色语音，就是那些音效，比如战斗刀剑声效，切换时间声效，无音区靠近的bgm这些

**Comment by TomyJan** [comment]
可以 qq/tg 私我我帮你解一下

**Comment by Ryuchen** [comment]
老哥，我怎么qq你呢？我qq：455480366，能麻烦你加我一下吗？大佬

**Comment by Ryuchen** [comment]
我从你blog那跳转Q群，显示加群校验失败(⊙o⊙)…
